#492 runnable_in_console option
wysohn/TriggerReactor pull request #493
Opened 2022-07-06 14:00 UTC by rkdrns4747

[Please Check This Comment](https://github.com/TriggerReactor/TriggerReactor/issues/492#issuecomment-1176256789)

2022-09-05 06:46 UTC, rkdrns4747 commented
> https://github.com/TriggerReactor/TriggerReactor/commits/development_separate_listeners

This PR #493 may also have some effects from the `development_separate_listener` update.

2022-09-06 13:13 UTC, rkdrns4747 commented
This PR is scheduled to be closed due to rebasing to PR #497, as soon as PR #501 being resolved.

2022-09-18 21:05 UTC, wysohn requested changes
Generally looking good

Perhaps it's better to push it to next version instead though

2022-09-18 21:05 UTC, wysohn commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/bridge/AbstractBukkitWrapper.java
> +    public abstract IConsoleCommandSender wrap(ConsoleCommandSender sender);
Is implementation for BukkitConsoleCommandSender differ between latest and legacy versions? Or we could just make it a concrete method

2022-09-18 21:05 UTC, wysohn commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/main/AbstractJavaPlugin.java
> -    public ICommandSender getConsoleSender() {
Same: leave it and change in next version

2022-09-18 21:05 UTC, wysohn commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/main/AbstractJavaPlugin.java
> -    public Object createPlayerCommandEvent(ICommandSender sender, String label, String[] args) {
Same: leave it and change in next version

2022-09-18 21:05 UTC, wysohn commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/main/BukkitTriggerReactorCore.java
> -    public Object createPlayerCommandEvent(ICommandSender sender, String label, String[] args) {
Same: leave it and change in next version

2022-10-29 12:27 UTC, nicosammito commented on bukkit/latest/src/main/java/io/github/wysohn/triggerreactor/bukkit/bridge/BukkitWrapper.java
> +    public IConsoleCommandSender wrap(ConsoleCommandSender sender) {return new BukkitConsoleCommandSender(sender);}
```suggestion
    public IConsoleCommandSender wrap(final ConsoleCommandSender sender) {return new BukkitConsoleCommandSender(sender);}
```

2022-10-29 12:27 UTC, nicosammito commented on bukkit/legacy/src/main/java/io/github/wysohn/triggerreactor/bukkit/bridge/BukkitWrapper.java
> +    public IConsoleCommandSender wrap(ConsoleCommandSender sender) {return new BukkitConsoleCommandSender(sender);}
```suggestion
    public IConsoleCommandSender wrap(final ConsoleCommandSender sender) {return new BukkitConsoleCommandSender(sender);}
```

2022-10-29 12:27 UTC, nicosammito commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/bridge/BukkitConsoleCommandSender.java
> +    public BukkitConsoleCommandSender(ConsoleCommandSender sender){
```suggestion
    public BukkitConsoleCommandSender(final ConsoleCommandSender sender){
```

2022-10-29 12:27 UTC, nicosammito commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/bridge/BukkitConsoleCommandSender.java
> +    public void sendMessage(String message) {
```suggestion
    public void sendMessage(final String message) {
```

2022-10-29 12:27 UTC, nicosammito commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/bridge/BukkitConsoleCommandSender.java
> +    public boolean hasPermission(String permission) {
```suggestion
    public boolean hasPermission(final String permission) {
```

2022-10-29 12:27 UTC, nicosammito commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/main/AbstractJavaPlugin.java
> +    public Object createCommandEvent(ICommandSender sender, String label, String[] args) {
```suggestion
    public Object createCommandEvent(final ICommandSender sender, final String label, final String[] args) {
```

2022-10-29 12:27 UTC, nicosammito commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/main/BukkitTriggerReactorCore.java
>      public Object createEmptyPlayerEvent(ICommandSender sender) {
```suggestion
    public Object createEmptyPlayerEvent(final ICommandSender sender) {
```

2022-10-29 12:27 UTC, nicosammito commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/main/BukkitTriggerReactorCore.java
> +    public Object createCommandEvent(ICommandSender sender, String label, String[] args) {
```suggestion
    public Object createCommandEvent(final ICommandSender sender, final String label, final String[] args) {
```

2022-10-29 12:27 UTC, nicosammito commented on bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/manager/trigger/CommandTriggerManager.java
> +        varMap.put("argslength", args.length);
```suggestion
        Map<String, Object> varMap = Map.of("isByPlayer", true, "sender", sender, "command", cmd, "args", args, "argslength", args.length);
```

2022-10-29 12:27 UTC, nicosammito commented on core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/command/CommandTrigger.java
> +    public void setConsoleAvailable(boolean bool){
```suggestion
    public void setConsoleAvailable(final boolean bool){
```

2023-08-13 22:14 UTC, wysohn commented
this branch is stale for long time and is unlikely cleanly merged

Suggested to create a new branch and replicate the changes there

2023-08-13 22:14 UTC, closed without merging